/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as EstimateIdRouteImport } from './routes/estimate.$id'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiImgRouteImport } from './routes/api.img'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateIdRoute = EstimateIdRouteImport.update({
  id: '/estimate/$id',
  path: '/estimate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/estimates': typeof EstimatesRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/videos': typeof VideosRoute
  '/api/img': typeof ApiImgRoute
  '/api/upload': typeof ApiUploadRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/estimates': typeof EstimatesRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/videos': typeof VideosRoute
  '/api/img': typeof ApiImgRoute
  '/api/upload': typeof ApiUploadRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/estimates': typeof EstimatesRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/videos': typeof VideosRoute
  '/api/img': typeof ApiImgRoute
  '/api/upload': typeof ApiUploadRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/estimates'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/service'
    | '/sitemap.xml'
    | '/stock'
    | '/videos'
    | '/api/img'
    | '/api/upload'
    | '/estimate/$id'
    | '/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/estimates'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/service'
    | '/sitemap.xml'
    | '/stock'
    | '/videos'
    | '/api/img'
    | '/api/upload'
    | '/estimate/$id'
    | '/review/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/estimates'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/service'
    | '/sitemap.xml'
    | '/stock'
    | '/videos'
    | '/api/img'
    | '/api/upload'
    | '/estimate/$id'
    | '/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EstimatesRoute: typeof EstimatesRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceRoute: typeof ServiceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockRoute: typeof StockRoute
  VideosRoute: typeof VideosRoute
  ApiImgRoute: typeof ApiImgRoute
  ApiUploadRoute: typeof ApiUploadRoute
  EstimateIdRoute: typeof EstimateIdRoute
  ReviewIdRoute: typeof ReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$id': {
      id: '/estimate/$id'
      path: '/estimate/$id'
      fullPath: '/estimate/$id'
      preLoaderRoute: typeof EstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EstimatesRoute: EstimatesRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceRoute: ServiceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockRoute: StockRoute,
  VideosRoute: VideosRoute,
  ApiImgRoute: ApiImgRoute,
  ApiUploadRoute: ApiUploadRoute,
  EstimateIdRoute: EstimateIdRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
